### ISSUE TITLE
restrictToHorizontalAxis and restrictToVerticalAxis should also lock auto scroll to that axis

### ISSUE THREAD

**Issue by Rinaldo** [clauderic/dnd-kit#1095]
When using the `restrictToHorizontalAxis` or `restrictToVerticalAxis` modifiers, auto scroll should be disabled for the other axis.

Steps to reproduce:
- go to the [Sortable - Horizontal - Locked Axis](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-horizontal--locked-axis) example
- add the following css with devtools
```css
main {
    height: 1000px;
    padding-top: 400px;
}
div[role=[button] {
    height: 40px !important;
}
```
- scroll down until the list is at the very top of the example canvas
- try to drag an item sideways and notice how easy it is to accidentally scroll the screen up
