### ISSUE TITLE
Is it possible to have custom placeholder when sorting items?

### ISSUE THREAD

**Issue by junqdu** [clauderic/dnd-kit#141]
Desired behavior:
![](https://user-images.githubusercontent.com/4250728/111679039-2220da80-87de-11eb-9696-ff1bd86a1fe8.png)

Codesandbox:
https://codesandbox.io/s/grid-view-multi-select-poc-3gpug?file=/src/Selectable.tsx

Current:
![Screen Shot 2021-03-18 at 8 26 51 PM (2)](https://user-images.githubusercontent.com/4250728/111732739-77d3a200-8833-11eb-8b73-ecad507e02e5.png)

@clauderic it seems like we can customize the DragOverlay, but not the placeholder in the list. Or maybe I didn't look close enough

**Comment by ranbena** [comment]
@junqdu there is no actual placeholder, but the dragged sortable item can made to look like a placeholder utilizing a few props. The example you provided already applies `opacity: 0.5` styling to the placeholder in `Item.module.scss` line 88, and so you can modify it to get your desired effect.

So to make the placeholder be a solid colored box with no content:
```css
/* Item.module.scss */

&.dragging:not(.dragOverlay) {
  background-color: #d2d7db; /* apply bg color */
  text-indent: -100vw; /* hide text */
  
  & > *,
  &.color:before {
    display: none; /* hide other content */
  }
}
```

[Here's a modified sandbox example](https://codesandbox.io/s/grid-view-multi-select-poc-forked-kt5oi?file=/src/Item.module.scss:1946-1957).
