### ISSUE TITLE
Drag position is not working when the style overflowing

### ISSUE THREAD

**Issue by irico3** [clauderic/dnd-kit#1474]
It appears that e.delta.x jumps when nearby content wraps while being dragged.
Is there any solution regarding this? thank you.

https://github.com/user-attachments/assets/a11c1dec-2385-4c1a-b987-6d79e98488b1

Also,  I have prepared a minimum repository that reproduces the behavior in the video.
https://github.com/irico3/overflow-dnd-kit-sample

Here is an excerpt from the repository code.

```typescript
function App() {
  const [width, setWidth] = useState(580);

  const [startWidth, setStartWidth] = useState(580);

  return (
    <DndContext
      onDragStart={() => {
        setStartWidth(width);
      }}
      onDragMove={(e) => {
        setWidth(startWidth + e.delta.x);
      }}
      modifiers={[restrictToHorizontalAxis]}
    >
      <div className="container">
        <div className="boxContainer" style={{ width: `${width}px` }}>
          <div className="box" />
          <div className="box" />
           ...
        </div>
        <Handler />
      </div>
    </DndContext>
  );
}

export default App;
```

```css
.box {
  width: 100px;
  height: 100px;
  background: lime;
}

.container {
  display: flex;
  justify-content: flex-start;
}

.boxContainer {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
  padding-left: 100px;
}

.handler {
  width: 30px;
  background: white;
}
```

MacOS:  Sonoma 14.5
Browser: Chrome 127.0.6533.101
@dnd-kit/core version: 6.1.0
