### ISSUE TITLE
Issue with clicking on the same Item twice freezes entire sortable list?

### ISSUE THREAD

**Issue by nicewaytodoit** [clauderic/dnd-kit#204]
I would appreciate a bit of help not sure what I am doing wrong,  trying to setup fairly simple example as below:
```js
import React, { useState } from 'react';
import { DndContext, DragOverlay, useDraggable } from '@dnd-kit/core';
import { SortableContext, useSortable } from '@dnd-kit/sortable';

import './App.css';

const LIST = [
    { id: 1, name: 'TEST 1' },
    { id: 2, name: 'TEST 2' },
    { id: 3, name: 'TEST 3' },
    { id: 4, name: 'TEST 4' },
    { id: 5, name: 'TEST 5' },
];

const Item = ({id, list}) => {
    const { attributes, listeners, setNodeRef, transform, transition } = useSortable({id: id});
    const item = list.find(ii => ii.id === id) || { name: 'UNKNONW' };
    return (
        <div
            ref={setNodeRef}
            className="app__item"
            {...listeners}
            {...attributes}
        >
            {item.name}
        </div>
    );
}

const App = () => {
    const [list, setList] = useState(LIST);
    const [num, setNum] = useState(0);
    const [activeId, setActiveId] = useState(null);

    const handleDragStart = (e) => {
        console.log('Start', e.active);
        setActiveId(e.active.id);
    };

    const handleDragEnd = (e) => {
        console.log('END', e);
        if (!e.over) return;
        setNum((p) => p+1);
        setActiveId(null);
        setList((prev) => {
            let lst = [...prev];
            const cut = lst.splice(lst.findIndex(a=>a.id===e.active.id), 1);
            lst.splice(lst.findIndex(a=>a.id===e.over.id)+1,0,{...cut[0]});
            console.log(cut, JSON.stringify(lst, null, 2));
            return [...lst];
        });
    };
    
    const handleDragMove = (e) => {
        // console.log(e);
    };
    const handleDragCancel = (e) => {
        console.log('CANCEL',e);
    };
      
    return (
        <div className="app">
            <DndContext
                onDragEnd={handleDragEnd}
                onDragStart={handleDragStart}
                onDragMove={handleDragMove}
                onDragCancel={handleDragCancel}
            >
                <SortableContext items={list}>
                    <div className="app__container">
                        {list.map((item) => {
                            return <Item key={item.id} id={item.id} list={list} />
                        })}
                    </div>
                </SortableContext>
                <DragOverlay>
                    {activeId ? <Item id={activeId} list={list} /> : null}
                </DragOverlay>
            </DndContext>
        </div>
    );
}

export default App;

```
As soon as any item is touched twice all items will stop working, any clue why?

**Comment by nicewaytodoit** [comment]
```css
.app {
  height: 100vh;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  
}

.app__container {
  border: 1px solid black;
  width: 500px;
  height: 600px;
  padding: 20px;
  user-select: none;
}

.app__item {
  border: 1px solid black;
  height: 30px;
  padding: 5px;
  width: 100%;
  margin: 10px 0;
  text-align: center;
  background-color: lightblue;
}

.my__drag {
  border: 1px solid black;
  background-color: blue;
}
```
